[package]
name = "task_management"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = "2.2.3"
dotenv = "0.15.0"
json = "0.12.4"
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.209"
serde_json = "1.0.127"
tokio = "1.40.0"
