name: CI

on:
  push:
    branches:
      - Main
  pull_request:
    branches:
      - main

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Make clean script executable
        run: chmod +x clean.sh

      - name: Run clean script
        run: ./clean.sh

  build-and-test:
    needs: clean
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - Module00
          - Module01/error
          - Module01/simple_calc
          - Module01/Todo
          # - Module02
          - Module02/Chatbot
          - Module02/gitCheck
          - Module02/Web1
          - Module02/Web2
          - Module02/Auth
          - Module02/auth_server
          # - Module03
          - Module03/data_vault
          - Module03/data_vault_exx
          # - Module05
          - Module03/cachecomponent
          - Module03/consolelog
          # Module 07
          - Module07/btreemap/src
          - Module07/valuetree
          # Module08
          - Module08/banking
          # Module09
          - Module09/rust_backend
          - Module09/tokenize
          # Module10
          - Module10/generic
          - Module10/performanceCheck
          
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build and test
        working-directory: ${{ matrix.module }}
        run: |
          cargo build --verbose
          cargo test --verbose
    
